server:
  address: localhost
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  redis:
    host: 127.0.0.1
    port: 6380
  cache:
    type: redis
    redis:
      time-to-live: 60000
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/ta
    username: the2792
    password: canyou12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 애플리케이션이 실행될때마다 테이블을 드랍하고 다시 생성
    properties:
      hibernate:
        default_batch_fetch_size: 1000 # 100~1000 사이
        # show_sql: true # 하이버네이트에서 실행되는 SQL문이 로그로 출력됨
        format_sql: true # 하이버네이트에서 실행되는 SQL문이 System.out 으로 출력됨
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400