version: '3.7'
services:
  database:
    container_name: docker-jwt-mysql
    image: mysql:5.7
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ta
      MYSQL_USER: the2792
      MYSQL_PASSWORD: canyou12
      MYSQL_ROOT_PASSWORD: canyou12
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6380:6379"